delete http://localhost:3003/api/blogs/623923e9694ac4e6c9633f92
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbnVzaW5nIiwiaWQiOiI2MjMyOTM2Y2VlM2U2ZWY3YTE0ZjJmNWUiLCJpYXQiOjE2NDc5MTIwNjcsImV4cCI6MTY0NzkxNTY2N30.3OlKDKMyZxFrrL6Y7kyFWD0veL3Km-T-exUtCpG4Xag