delete http://localhost:3003/api/blogs/6232a3bd5297d5611f5cb6d6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbnVzaW5nIiwiaWQiOiI2MjMyOTM2Y2VlM2U2ZWY3YTE0ZjJmNWUiLCJpYXQiOjE2NDc0OTg0OTcsImV4cCI6MTY0NzUwMjA5N30.qRQ5VCT4ENVtqcviqTGUF5Wf9KcRScKnGU8rmb9CA2c